dist: trusty
sudo: require

language: clojure

before_install:
  - sudo apt-get update

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - sudo apt-get install leiningen
    
script:
  - lein test